name: MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0-dev.2666+1e207f1ed
      
      - name: Install deps
        env:
          VLC_PLUGIN_PATH: /Applications/VLC.app/Contents/MacOS/lib
        run: |
            brew install sdl2 && \
            brew install --cask VLC && \
            sudo ln -s /Applications/VLC.app/Contents/MacOS/include/vlc /usr/local/include/ && \
            sudo ln -s /Applications/VLC.app/Contents/MacOS/lib/* /usr/local/lib/

      - name: Build
        run: zig build -Doptimize=ReleaseSafe -fsummary -freference-trace
      
      - name: run print_version (example)
        run: zig build run -Doptimize=ReleaseSafe
