name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Install dependences
        run: |
            sudo apt update
            sudo apt install libvlc-dev libsdl2-dev -y

      - name: Build Summary
        run: zig build --summary all -freference-trace

      - name: run print_version (example)
        run: zig build run
