name: MSYS2 (MingW)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: CLANG64, arch: x86_64, prefix: /clang64 },
          { msystem: CLANG32, arch: i686, prefix: /clang32   }
        ]
    
    steps:
      - uses: actions/checkout@v3
        with:
          path: temp
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0-dev.2666+1e207f1ed
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          path-type: inherit
          location: D:\
          install: git mingw-w64-clang-${{ matrix.arch }}-vlc
          update: true
      
      # - name: install windows sdk
      #   run: choco install windows-sdk-10.0
      
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: Build & Tests (x86)
        shell: msys2 {0}
        if: ${{ matrix.arch == 'i686' }}
        run: |
            cd /C/_
            zig build -fsummary -freference-trace -Doptimize=ReleaseSafe -Dtarget=x86-windows-gnu
            zig build run -Doptimize=ReleaseSafe -Dtarget=x86-windows-gnu
        
      - name: Build & Tests (x86_x64)
        shell: msys2 {0}
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
            cd /C/_
            zig build -fsummary -freference-trace -Doptimize=ReleaseSafe -Dtarget=native-windows-gnu
            zig build run -Doptimize=ReleaseSafe -Dtarget=native-windows-gnu